Solved comparemax
nick3point5/DA_problems pull request #4
Opened 2024-01-04 22:03 UTC by DomineersXII

2024-01-04 23:09 UTC, nick3point5 commented on problems/1_find_maximum_value/1/compareMax/compareMax.js
> +	if (a > b) {
You can combine the conditions (a > b) and (b == a)/(a == b) with (a >= b)

2024-01-04 23:40 UTC, nick3point5 requested changes
There are a few issues with the code but they get the job done. I would like you to response to some of my comments before I approve.

2024-01-04 23:40 UTC, nick3point5 commented on problems/2_factorial/3/factorial/factorial.js
> +        var totalNumber = 1
I don't ever recommend using "var" for variable declaration. You should be using "let" instead.

2024-01-04 23:40 UTC, nick3point5 commented on problems/3_series/2/rounding/rounding.js
> +		var rePrecise = 10 ** Math.abs(precision)
Again, I don't recommend "var"

2024-01-04 23:40 UTC, nick3point5 commented on problems/2_factorial/3/factorial/factorial.js
> +	} else if (isNaN(n) || n < 0 || (n - Math.floor(n)) !== 0) {
isNaN(n) is redundant  "(n - Math.floor(n)) !== 0" covers that cause since "NaN !== 0" is true

2024-01-04 23:40 UTC, nick3point5 commented on problems/1_find_maximum_value/1/compareMax/compareMax.js
> +	} else if (b == a) {
You should always be defaulting to using strict equality "===" instead of coercive "=="

2024-01-04 23:40 UTC, nick3point5 commented on problems/2_factorial/3/factorial/factorial.js
> +		throw new Error(`Not a Number`);
Error message is incorrect  -5 is a number and will throw an error. Be careful incorrect error messages can be worse than no message, because it will lead you down the wrong path to fix it.

2024-01-04 23:40 UTC, nick3point5 commented on problems/2_factorial/3/factorial/factorial.js
> +            totalNumber = Number(totalNumber)  * Number(factorialArray[j])
You shouldn't need to convert the totalNumber or factorialArray to numbers. That was handled by the throw above.

2024-01-04 23:40 UTC, nick3point5 commented on problems/3_series/3/sumSeries/sumSeries.js
> +	}
Same issues as problems/2_factorial/3/factorial/factorial.js

2024-01-04 23:40 UTC, nick3point5 commented on problems/2_factorial/3/factorial/factorial.js
> +            totalNumber = Number(totalNumber)  * Number(factorialArray[j])
@DomineersXII Why did you decide of type cast (convert type) the values like this?

2024-01-05 03:02 UTC, nick3point5 commented on problems/2_factorial/2/throwNegative/throwNegative.js
> +		throw new console.error();
this is incorrect. It crashes the program not really throwing an error.

2024-01-07 22:41 UTC, DomineersXII commented on problems/2_factorial/3/factorial/factorial.js
> +            totalNumber = Number(totalNumber)  * Number(factorialArray[j])
I used the same code in the advent of code day 1 so I never changed it. Because in advent of code day 1 I had to convert the values to numbers.

2024-01-07 22:41 UTC, DomineersXII commented on problems/1_find_maximum_value/1/compareMax/compareMax.js
> +	} else if (b == a) {
What is the difference between loose and strict equality? I don't really understand it.

2024-01-08 00:16 UTC, nick3point5 commented on problems/1_find_maximum_value/1/compareMax/compareMax.js
> +	} else if (b == a) {
In JavaScript, the loose equality doesn't properly maintain typings. This is lead to unexpected bugs. For example:
`1 == "1" // true`
`true  == "1" // true`
The loose equality will try to type coercion to try to match the data types like Numbers => Strings before checking equality. Strict equality returns false if the types are mismatched.

2024-01-25 21:51 UTC, closed without merging